{
    'name': 'Product Barcode',
    'version': '17.0.1.0',
    'category': 'Module',
    'summary': 'Product Barcode',
    'description': """
        Product barcode by Anggit
    """,
    'website': '',
    'author': 'Anggit',
    'depends': ['web','base', 'product', 'account', 'purchase', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'data/stock_opname_data.xml',
        'data/product_borrowing_data.xml',
        'reports/stock_opname_report.xml',
        'reports/product_borrowing_report.xml',
        'data/inventory_return_product_data.xml',
        'views/stock_picking_view.xml',
        'views/stock_opname_view.xml',
        'reports/inventory_receipt_barcode_report.xml',
        'views/inventory_opname_history_view.xml',
        'views/product_borrowing_view.xml',
        'views/product_borrowing_return_wizard_view.xml',
        'views/product_product_view.xml',
        'views/inventory_return_product_views.xml',
    ],
    'installable': True,
    'license': 'OEEL-1',
}